fieldLayouts:
  f7bff873-6ba8-492d-8147-9da5b00bf699:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 332642bf-7f08-4ec0-b611-fafdd5fd5643
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd8dd0d9-5370-46bf-b684-78840bf9e9b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: bannerImage
hasUrls: true
name: 'Banner Image'
settings:
  path: images/banner
sortOrder: 1
type: craft\volumes\Local
url: /images/banner
